import type { AcademicChangeKind, AcademicChangeWorkflowStatus, Prisma, Role } from '@prisma/client';
export type GradePayload = {
    studentId: string;
    courseId: string;
    teacherId: string;
    evaluationType: string;
    title: string;
    score: number;
    maxScore: number;
    coefficient: number;
    date: string | Date;
    comments?: string | null;
};
export type ReportCardPayload = {
    studentId: string;
    period: string;
    academicYear: string;
    average: number;
    rank?: number | null;
    comments?: string | null;
    published?: boolean;
};
export declare function resolveStudentClassId(studentId: string): Promise<string | null>;
export declare function gradeToPayload(grade: {
    studentId: string;
    courseId: string;
    teacherId: string;
    evaluationType: string;
    title: string;
    score: number;
    maxScore: number;
    coefficient: number;
    date: Date;
    comments: string | null;
}): GradePayload;
export declare function createGradeChangeRequest(params: {
    kind: AcademicChangeKind;
    requestedByUserId: string;
    gradeId?: string | null;
    studentId: string;
    payload: GradePayload;
    previousPayload?: GradePayload | null;
}): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function createReportCardChangeRequest(params: {
    kind: AcademicChangeKind;
    requestedByUserId: string;
    reportCardId?: string | null;
    studentId: string;
    payload: ReportCardPayload;
    previousPayload?: ReportCardPayload | null;
}): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function canUserApproveRequest(userId: string, role: Role, request: {
    status: AcademicChangeWorkflowStatus;
    classId: string | null;
}): Promise<boolean>;
export declare function listPendingForUser(userId: string, role: Role): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    student: ({
        class: {
            id: string;
            level: string;
            name: string;
        } | null;
        user: {
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        userId: string;
        studentId: string;
        nfcId: string | null;
        biometricId: string | null;
        faceDescriptor: Prisma.JsonValue | null;
        faceEnrolledAt: Date | null;
        dateOfBirth: Date;
        birthPlace: string | null;
        isRepeating: boolean;
        gender: import(".prisma/client").$Enums.Gender;
        address: string | null;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        emergencyContact2: string | null;
        emergencyPhone2: string | null;
        medicalInfo: string | null;
        allergies: string | null;
        specialNeeds: string | null;
        nationalMatricule: string | null;
        digitalCardPublicId: string | null;
        archivedAt: Date | null;
        lastReenrollmentAt: Date | null;
        enrollmentDate: Date;
        enrollmentStatus: import(".prisma/client").$Enums.EnrollmentStatus;
        isActive: boolean;
        schoolId: string | null;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        classGroupId: string | null;
        stateAssignment: string | null;
    }) | null;
}[]>;
export declare function listRequestsByRequester(userId: string): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
    student: ({
        class: {
            id: string;
            level: string;
            name: string;
        } | null;
        user: {
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        userId: string;
        studentId: string;
        nfcId: string | null;
        biometricId: string | null;
        faceDescriptor: Prisma.JsonValue | null;
        faceEnrolledAt: Date | null;
        dateOfBirth: Date;
        birthPlace: string | null;
        isRepeating: boolean;
        gender: import(".prisma/client").$Enums.Gender;
        address: string | null;
        emergencyContact: string | null;
        emergencyPhone: string | null;
        emergencyContact2: string | null;
        emergencyPhone2: string | null;
        medicalInfo: string | null;
        allergies: string | null;
        specialNeeds: string | null;
        nationalMatricule: string | null;
        digitalCardPublicId: string | null;
        archivedAt: Date | null;
        lastReenrollmentAt: Date | null;
        enrollmentDate: Date;
        enrollmentStatus: import(".prisma/client").$Enums.EnrollmentStatus;
        isActive: boolean;
        schoolId: string | null;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        classGroupId: string | null;
        stateAssignment: string | null;
    }) | null;
}[]>;
export declare function applyApprovedRequest(requestId: string): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
} | null>;
export declare function approveAcademicChangeRequest(params: {
    requestId: string;
    userId: string;
    role: Role;
    note?: string;
}): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
} | null>;
export declare function rejectAcademicChangeRequest(params: {
    requestId: string;
    userId: string;
    role: Role;
    reason?: string;
}): Promise<{
    id: string;
    target: import(".prisma/client").$Enums.AcademicChangeTarget;
    kind: import(".prisma/client").$Enums.AcademicChangeKind;
    status: import(".prisma/client").$Enums.AcademicChangeWorkflowStatus;
    studentId: string;
    classId: string | null;
    gradeId: string | null;
    reportCardId: string | null;
    payload: Prisma.JsonValue;
    previousPayload: Prisma.JsonValue | null;
    requestedByUserId: string;
    requestedAt: Date;
    mainTeacherApprovedAt: Date | null;
    mainTeacherApprovedByUserId: string | null;
    mainTeacherNote: string | null;
    educatorApprovedAt: Date | null;
    educatorApprovedByUserId: string | null;
    educatorNote: string | null;
    studiesDirectorApprovedAt: Date | null;
    studiesDirectorApprovedByUserId: string | null;
    studiesDirectorNote: string | null;
    rejectedAt: Date | null;
    rejectedByUserId: string | null;
    rejectionReason: string | null;
    appliedAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function workflowStatusLabel(status: AcademicChangeWorkflowStatus): string;
//# sourceMappingURL=academic-change-request.util.d.ts.map